# Linear Algebra Refresher

In [2]:
import numpy as np

## Vector Operations

In [3]:
u = np.array([2,4,5,6])

In [4]:
u

array([2, 4, 5, 6])

In [5]:
v = np.array([1, 0, 0, 2])

In [6]:
v

array([1, 0, 0, 2])

In [7]:
u + v

array([3, 4, 5, 8])

In [8]:
u + v

array([3, 4, 5, 8])

In [9]:
u.shape[0]

4

## Multiplication

In [10]:
u.shape[0]

4

In [11]:
def vect_vect_mult(u, v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]

    result = 0.0

    for i in range(n):
        result += u[i] * v[i]

    return result

In [12]:
vect_vect_mult(u,v)

np.float64(14.0)

In [13]:
u.dot(v)

np.int64(14)

In [14]:
u.dot(v)+10

np.int64(24)

In [15]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1]
])

In [16]:
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [17]:
U.shape

(3, 4)

In [18]:
U[0]

array([2, 4, 5, 6])

In [19]:
def mat_vect_mult(U,v):
    assert U.shape[1] == v.shape[0]

    num_rows = U.shape[0]
    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vect_vect_mult(U[i], v)
    return result

In [20]:
mat_vect_mult(U,v)

array([14.,  5.,  5.])

## Matrix Matrix Multiplication

In [21]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 2, 1],
    [2, 1, 0]
])

In [22]:
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [28]:
def mat_mat_mult(U,V):
    assert U.shape[1] == V.shape[0]

    num_rows = U.shape[0]
    num_cols = V.shape[1]

    result = np.zeros((num_rows, num_cols))

    for i in range(num_rows):
        vi = V[:,i]
        result[:,i] = mat_vect_mult(U,vi)
    return result

In [29]:
mat_mat_mult(U,V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [30]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

## Identity Matrix

In [31]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [32]:
I = np.eye(3)

In [33]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

## Inverse Matrix

In [34]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [35]:
Vs = V[[0, 1, 3]]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [2. , 1. , 0. ]])

In [37]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 1. , -2. ,  0. ],
       [-2. ,  4. ,  1. ],
       [ 1. , -1. , -0.5]])

In [38]:
Vs_inv.dot(I)

array([[ 1. , -2. ,  0. ],
       [-2. ,  4. ,  1. ],
       [ 1. , -1. , -0.5]])

In [39]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])