## Numpy
- Creating arrays
- Multi dimensional arrays
- randomly generated arrays
- element-wise operations
- Summarizing operations

In [1]:
import numpy as np

## Create Arrays

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(10,3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [5]:
a = np.array([1,2,3,4,5])

In [6]:
a

array([1, 2, 3, 4, 5])

In [7]:
a[2]

np.int64(3)

In [8]:
a[2] = 10

In [9]:
a

array([ 1,  2, 10,  4,  5])

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [14]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## Multi-dimensional Arrays

In [15]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [17]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [18]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
n[0,1]

np.int64(2)

In [20]:
n[0]

array([1, 2, 3])

In [21]:
n[1]

array([4, 5, 6])

In [22]:
n[2]

array([7, 8, 9])

In [31]:
n[0] = np.zeros(3)

In [32]:
n

array([[0, 0, 0],
       [1, 1, 1],
       [7, 8, 1]])

In [33]:
n[:,1]

array([0, 1, 8])

In [34]:
n[:,2] = np.ones(3)

In [35]:
n

array([[0, 0, 1],
       [1, 1, 1],
       [7, 8, 1]])

## Randomly Generated Arrays

In [42]:
np.random.seed(2)
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [44]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [47]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

## Element-wise operations

In [48]:
elt = np.arange(5)
elt

array([0, 1, 2, 3, 4])

In [49]:
elt+1

array([1, 2, 3, 4, 5])

In [50]:
elt*5

array([ 0,  5, 10, 15, 20])

In [52]:
elt/5

array([0. , 0.2, 0.4, 0.6, 0.8])

In [53]:
(10 + (elt*2)) ** 2 / 100

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [55]:
b = elt + 10 * elt

## Comparison Operations

In [56]:
elt >= 2

array([False, False,  True,  True,  True])

In [57]:
elt > b

array([False, False, False, False, False])

In [58]:
b[b > elt]

array([11, 22, 33, 44])

In [59]:
b

array([ 0, 11, 22, 33, 44])

In [60]:
b[b>10]

array([11, 22, 33, 44])

In [61]:
b.sum()

np.int64(110)

In [62]:
b.min()

np.int64(0)

In [63]:
b.max()

np.int64(44)