# Intro to Numpy

In [1]:
import numpy as np

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [7]:
a = np.array([1,2,3,4,5,7,12])

In [8]:
a

array([ 1,  2,  3,  4,  5,  7, 12])

In [9]:
a[2]

np.int64(3)

In [10]:
a[2] = 10

In [11]:
a

array([ 1,  2, 10,  4,  5,  7, 12])

In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [16]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [17]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

## Multi-dimensional Arrays

In [19]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [21]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [22]:
n[0]

array([1, 2, 3])

In [23]:
n[2,1]

np.int64(8)

In [26]:
n[:, 1]

array([2, 5, 8])

In [27]:
n[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
np.random.rand(5,2)

array([[0.23599786, 0.77266253],
       [0.84875694, 0.134691  ],
       [0.56926058, 0.31780593],
       [0.58067333, 0.77774046],
       [0.40981443, 0.83976397]])

In [29]:
np.random.rand(5,2)

array([[0.3920729 , 0.85560134],
       [0.34970902, 0.87096715],
       [0.03614871, 0.46662149],
       [0.84190448, 0.65904707],
       [0.6650338 , 0.55729887]])

In [30]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [31]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [32]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

In [34]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [35]:
a+1

array([1, 2, 3, 4, 5])

In [36]:
a*2

array([0, 2, 4, 6, 8])

In [38]:
b = 10 + (a*2)

In [39]:
a + b

array([10, 13, 16, 19, 22])

In [40]:
a >= 2

array([False, False,  True,  True,  True])

In [41]:
a > b

array([False, False, False, False, False])

In [42]:
a[a > 2]

array([3, 4])

In [43]:
a.min()

np.int64(0)

In [44]:
a.max()

np.int64(4)

In [45]:
a.mean()

np.float64(2.0)

In [46]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
n.sum()

np.int64(45)

In [48]:
n.min()

np.int64(1)

In [49]:
n.max()

np.int64(9)

## Vector Operations

In [50]:
u = np.array([2, 4, 5, 6])

In [51]:
u

array([2, 4, 5, 6])

In [52]:
v = np.array([1, 0, 0, 2])

In [53]:
v

array([1, 0, 0, 2])

In [54]:
u + v

array([3, 4, 5, 8])

In [55]:
u * v

array([ 2,  0,  0, 12])

In [56]:
def vect_vect_mult(u,v):
    assert u.shape[0] == v.shape[0]
    n = u.shape[0]
    result = 0.0
    for i in range(n):
        result += u[i] * v[i]
    return result

In [57]:
vect_vect_mult(u,v)

np.float64(14.0)

In [58]:
u.dot(v)

np.int64(14)

In [59]:
u

array([2, 4, 5, 6])

In [60]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1]
])

In [62]:
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [63]:
v = np.array([1, 0.5, 2, 1])

In [64]:
v

array([1. , 0.5, 2. , 1. ])

In [65]:
def mat_vec_mult(U,v):
    assert U.shape[1] == v.shape[0]
    num_rows = U.shape[0]
    result = np.zeros(num_rows)
    for i in range(num_rows):
        result[i] = vect_vect_mult(U[i],v)
    return result

In [66]:
mat_vec_mult(U,v)

array([20. ,  6. ,  8.5])

In [67]:
U.dot(v)

array([20. ,  6. ,  8.5])

In [68]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 2, 1],
    [2, 1, 0]
])

In [69]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [74]:
def mat_mat_mult(U,V):
    assert U.shape[1] == V.shape[0]
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    result = np.zeros((num_rows, num_cols))
    for j in range(num_cols):
        vj = V[:, j]
        Uvj = mat_vec_mult(U, vj)
        result[:, j] = Uvj
    return result

In [75]:
mat_mat_mult(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [76]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

## Identity Matrix (I)

In [77]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [78]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Inverse matrix

In [79]:
Vs = V[[0, 1, 2]]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [81]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])